server:
    port: 8080

spring:
    application:
        name: GicDemo
    profiles:
        active: default
logging:
    level:
        org:
            springframework:
                web:
                    servlet:
                        resource: ERROR
