name: CiCd test

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: mazon Linux 2023

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker Image
        run: |
          docker build -t gic-cicd .

      - name: Push Image to ECR or Deploy Directly
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/my-java-app
            git pull origin main || true

            # Stop and remove old container/image
            docker stop my-java-app || true
            docker rm my-java-app || true

            # Build new image from pulled code
            docker build -t my-java-app .

            # Run new container
            docker run -d --name my-java-app -p 8080:8080 my-java-app
